apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab
  labels:
    app: gitlab-runner
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      initContainers:
        - name: init-runner
          image: gitlab/gitlab-runner:latest
          args:
            - register
          env:
            - name: CI_SERVER_URL
              value: XXXXXXXX
            - name: REGISTER_NON_INTERACTIVE
              value: "true"
            - name: REGISTRATION_TOKEN
              value: XXXXXXXX
            - name: RUNNER_EXECUTOR
              value: kubernetes
            - name: RUNNER_REQUEST_CONCURRENCY
              value: "4"
            # Must use privileged mode for docker-in-docker
            - name: KUBERNETES_PRIVILEGED
              value: "true"
            # More variables as needed (see below)
          volumeMounts:
            - mountPath: /etc/gitlab-runner
              name: config
            - mountPath: /etc/ssl/certs
              name: cacerts
              readOnly: true
        - name: init-runner-volume
          image: alpine
          command: ["sh", "-c"]
          # Append hostpath mount to configuration because there is no env variable for it
          # https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2578
          args:
            - |
              cat <<EOF >> /etc/gitlab-runner/config.toml
                [[runners.kubernetes.volumes.host_path]]
                name = "docker-sock"
                mount_path = "/var/run/docker.sock"
                host_path = "/var/run/docker.sock"
              EOF
          volumeMounts:
            - mountPath: /etc/gitlab-runner
              name: config
      containers:
        - name: runner
          image: gitlab/gitlab-runner:latest
          args:
            - run
          volumeMounts:
            - mountPath: /etc/gitlab-runner
              name: config
            - mountPath: /etc/ssl/certs
              name: cacerts
              readOnly: true
      volumes:
        - name: cacerts
          hostPath:
            path: /usr/share/ca-certificates/mozilla
        - name: config
          emptyDir: {}

